version: '3'
services:
  keycloak:
    container_name: keycloak3
    image: quay.io/keycloak/keycloak:23.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # DEBUG_PORT: '*:8787'
      DEBUG: 'true'
    command: ['start-dev', '--debug', '--import-realm', '--features=client-policies', '--http-relative-path=/auth']
    ports:
      - 8080:8080
      # - 8443:8443
      # - 8787:8787
    volumes:
    - ./target/keycloak-restrict-client-auth.jar:/home/lnv112/Documents/HealthEMR/keycloak-restrict-client-auth/keycloak-restrict-client-auth.jar
    - ./src/test/resources/:/opt/keycloak/data/import
