version: "3.9"
services:
  
  postgres:
    container_name: healthemr-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5444:5432"
    networks:
      - healthemr-backend

  keycloak:
      container_name: healthemr-iam
      image: jboss/keycloak:15.0.2

      command:
        -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled
        -Djboss.http.port=8080
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: healthemr-db
        DB_DATABASE: postgres
        DB_USER: postgres
        DB_SCHEMA: public
        DB_PASSWORD: postgres
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_LOGLEVEL: ALL
        KC_LOGL_EVEL: ALL
        ROOT_LOGLEVEL: ALL
        # KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        # KEYCLOAK_REALM_RSA_PUBLIC_KEY: ${KEYCLOAK_REALM_RSA_PUBLIC_KEY}
        # KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
        # KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8090:8080
      volumes:
        - ./healthemr-dev.json:/tmp/realm.json
      networks:
        - healthemr-backend



volumes:
  postgres-db:
    driver: local
 
networks:
  healthemr-backend:
    name: healthemr-backend

