version: "3.9"
services:
  
  postgres:
    container_name: healthemr-db-org
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5449:5432"
    networks:
      - healthemr-backend

  keycloak:
      container_name: healthemr-iam-org
      image: quay.io/phasetwo/phasetwo-keycloak:22.0.3

      # command:
        # ['start-dev --import-realm --http-relative-path=/auth']
      command: 
        -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled start-dev --import-realm --http-relative-path=/auth
      environment:
        KC_DB: postgres
        # KC_DB_URL_HOST: keycloak-postgres
        # KC_DB_HOST: postgres
        KC_DB_USERNAME: postgres
        KC_DB_PASSWORD: postgres
        KC_DB_SCHEMA: public
        # KC_DB_URL_DATABASE: postgres
        # KC_PROXY: edge
        # KC_HOSTNAME_STRICT: false
        KC_DB_URL: jdbc:postgresql://healthemr-db-org:5432/postgres
        # DB_VENDOR: POSTGRES
        # DB_ADDR: healthemr-db
        # DB_DATABASE: postgres
        # DB_USER: postgres
        # DB_SCHEMA: public
        # DB_PASSWORD: postgres
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KEYCLOAK_LOGLEVEL: ALL
        KC_LOGL_EVEL: ALL
        ROOT_LOGLEVEL: ALL
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8090:8080
      volumes:
        - ./healthemr-dev.json:/tmp/realm.json
      networks:
        - healthemr-backend



volumes:
  postgres-db:
    driver: local
 
networks:
  healthemr-backend:
    name: healthemr-backend
