version: "3.9"
services:
  postgres:
    container_name: postgres_db
    image: "postgres:13.2"
    env_file:
      - ./database.dev.env
    networks:
      - backend
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - "8710:5432"
  # pgadmin:
  #   container_name: pgadmin
  #   image: "dpage/pgadmin4:5.1"
  #   env_file:
  #     - ./database.dev.env
  #   ports:
  #     - "127.0.0.1:5050:80"
  #   networks:
  #     - backend
  keycloak:
    container_name: keycloak
    image: "jboss/keycloak:15.0.2"
    depends_on:
      - "postgres"
    env_file:
      - ./keycloak.dev.env
    ports:
      - "8180:8080"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge