version: '3.9'
services:
  
  postgres:
      container_name: healthemr-db-1
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        PGDATA: /data/postgres
      volumes:
        - postgres-db:/data/postgres
      ports:
        - "5457:5432"
      networks:
        - healthemr-backend

  keycloak:
    container_name: keycloak1
    image: quay.io/keycloak/keycloak:23.0.0
    environment:
      KC_DB: postgres
      # KC_DB_USERNAME: postgres
      # KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://healthemr-db-1:5432/postgres?user=postgres&password=postgres&ssl=false
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: ALL
      KC_LOGL_EVEL: ALL
      ROOT_LOGLEVEL: ALL
    command: 
      -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled start-dev
        -Djboss.http.port=8080 -Dkeycloak.profile.feature.scripts=enabled --http-relative-path=/auth
    ports:
      - 8080:8080
      # - 8443:8443
      # - 8787:8787
    volumes:
    - ./target/keycloak-restrict-client-auth.jar/keycloak-restrict-client-auth.jar:/opt/keycloak/providers/keycloak-restrict-client-auth.jar
    # - ./src/test/resources/:/opt/keycloak/data/import
    networks:
      - healthemr-backend



volumes:
  postgres-db:
    driver: local
 
networks:
  healthemr-backend:
    name: healthemr-backend

